---
version: '2.4'

services:
  watch:
    image: node:15.1.0-buster-slim
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      TERM: xterm
      TZ: Europe/Helsinki
    command:
      - bash
      - -e
      - -c
      - |
        npm install --no-save;
        while clear; do
          echo;
          node index.js;
          sleep 600;
        done
